build:
  version: "1.0"
loans:
  message: "Welcome to EazyBank Loans related Prod APIs"
  contactDetails:
    name: "Ravindra - Developer"
    email: "ravindra@eazybank.com"
  onCallSupport:
    - (940) 555-1234
    - (940) 523-1345